"""Core types for the Minsky Society of Mind architecture."""

from dataclasses import dataclass, field
from enum import Enum
from typing import Any
from datetime import datetime

# Message length constraint (~256 chars ≈ 64 tokens).
# Configurable via set_message_max_length() before orchestrator starts.
MESSAGE_MAX_LENGTH = 256


def set_message_max_length(n: int) -> None:
    """Override the between-room message length limit."""
    global MESSAGE_MAX_LENGTH
    MESSAGE_MAX_LENGTH = n


class RoomType(Enum):
    SENSORY = "sensory"
    PLANNING = "planning"
    MOTOR = "motor"
    EXTERNAL = "external"  # Messages from/to the outside world


class MessageType(Enum):
    # Sensory messages
    PERCEPTION = "perception"  # Raw input from the world
    ATTENTION_RESPONSE = "attention_response"  # Response to attention request
    TOOL_OUTPUT = "tool_output"  # Output from a tool (Motor -> Sensory)

    # Planning messages
    ATTENTION_REQUEST = "attention_request"  # Request sensory to focus on something
    HYPOTHESIS = "hypothesis"  # A hypothesis about the situation
    PLAN = "plan"  # A plan with expected value
    MOTOR_COMMAND = "motor_command"  # High-level instruction to motor

    # Motor messages
    ACTION = "action"  # Actual action taken in the world
    ACTION_RESULT = "action_result"  # Result of attempting an action
    TOOL_CALL = "tool_call"  # Motor is calling a tool (for logging)

    # System messages
    CYCLE_START = "cycle_start"
    CYCLE_END = "cycle_end"


def truncate_message(content: str, max_length: int | None = None) -> str:
    """Truncate message content to max length, adding ellipsis if needed."""
    if max_length is None:
        max_length = MESSAGE_MAX_LENGTH
    if len(content) <= max_length:
        return content
    return content[:max_length - 3] + "..."


@dataclass
class Message:
    """A message passed between rooms in the Society of Mind.

    Between-room messages are limited to MESSAGE_MAX_LENGTH characters.
    External messages, tool calls, and tool outputs are NOT truncated.
    """

    content: str
    source: RoomType
    target: RoomType
    message_type: MessageType
    cycle: int = 0
    timestamp: datetime = field(default_factory=datetime.now)
    metadata: dict[str, Any] = field(default_factory=dict)

    _EXEMPT_TYPES = frozenset({
        MessageType.TOOL_OUTPUT,
        MessageType.TOOL_CALL,
    })

    def __post_init__(self):
        """Enforce message length limit on between-room messages only."""
        if (self.source == RoomType.EXTERNAL
                or self.target == RoomType.EXTERNAL
                or self.message_type in self._EXEMPT_TYPES):
            return
        self.content = truncate_message(self.content)

    def __str__(self) -> str:
        return f"[{self.source.value} -> {self.target.value}] ({self.message_type.value}): {self.content}"


@dataclass
class InternalMessage:
    """In-room message between left and right agents.

    Truncated to MESSAGE_MAX_LENGTH, same limit as between-room messages.
    """
    content: str
    agent: str  # "left" or "right"
    room_type: RoomType
    cycle: int = 0

    def __post_init__(self):
        self.content = truncate_message(self.content)


@dataclass
class RoomState:
    """State maintained by a room across cycles."""

    room_type: RoomType
    message_history: list[Message] = field(default_factory=list)
    internal_history: list[InternalMessage] = field(default_factory=list)
    current_context: str = ""
    metadata: dict[str, Any] = field(default_factory=dict)

    def add_message(self, message: Message) -> None:
        self.message_history.append(message)

    def get_recent_messages(self, n: int = 10) -> list[Message]:
        return self.message_history[-n:]

    def add_internal(self, msg: InternalMessage) -> None:
        """Add an internal message with sliding window (keep last 20)."""
        self.internal_history.append(msg)
        if len(self.internal_history) > 20:
            self.internal_history = self.internal_history[-20:]


@dataclass
class Hypothesis:
    """A hypothesis generated by the Planning room."""

    description: str
    confidence: float  # 0.0 to 1.0
    supporting_evidence: list[str] = field(default_factory=list)


@dataclass
class Plan:
    """A plan generated by the Planning room."""

    hypothesis: Hypothesis
    steps: list[str]
    expected_value: float  # Predicted value/success probability
    reasoning: str = ""
