"""Core types for the Minsky Society of Mind architecture."""

from dataclasses import dataclass, field
from enum import Enum
from typing import Any
from datetime import datetime


class RoomType(Enum):
    SENSORY = "sensory"
    PLANNING = "planning"
    MOTOR = "motor"
    EXTERNAL = "external"  # Messages from/to the outside world


class MessageType(Enum):
    # Sensory messages
    PERCEPTION = "perception"  # Raw input from the world
    ATTENTION_RESPONSE = "attention_response"  # Response to attention request
    TOOL_OUTPUT = "tool_output"  # Output from a tool (Motor -> Sensory)

    # Planning messages
    ATTENTION_REQUEST = "attention_request"  # Request sensory to focus on something
    HYPOTHESIS = "hypothesis"  # A hypothesis about the situation
    PLAN = "plan"  # A plan with expected value
    MOTOR_COMMAND = "motor_command"  # High-level instruction to motor

    # Motor messages
    ACTION = "action"  # Actual action taken in the world
    ACTION_RESULT = "action_result"  # Result of attempting an action
    TOOL_CALL = "tool_call"  # Motor is calling a tool (for logging)

    # System messages
    CYCLE_START = "cycle_start"
    CYCLE_END = "cycle_end"


@dataclass
class Message:
    """A message passed between rooms in the Society of Mind."""

    content: str
    source: RoomType
    target: RoomType
    message_type: MessageType
    cycle: int = 0
    timestamp: datetime = field(default_factory=datetime.now)
    metadata: dict[str, Any] = field(default_factory=dict)

    def __str__(self) -> str:
        return f"[{self.source.value} -> {self.target.value}] ({self.message_type.value}): {self.content[:100]}"


@dataclass
class RoomState:
    """State maintained by a room across cycles."""

    room_type: RoomType
    message_history: list[Message] = field(default_factory=list)
    current_context: str = ""
    metadata: dict[str, Any] = field(default_factory=dict)

    def add_message(self, message: Message) -> None:
        self.message_history.append(message)

    def get_recent_messages(self, n: int = 10) -> list[Message]:
        return self.message_history[-n:]


@dataclass
class Hypothesis:
    """A hypothesis generated by the Planning room."""

    description: str
    confidence: float  # 0.0 to 1.0
    supporting_evidence: list[str] = field(default_factory=list)


@dataclass
class Plan:
    """A plan generated by the Planning room."""

    hypothesis: Hypothesis
    steps: list[str]
    expected_value: float  # Predicted value/success probability
    reasoning: str = ""
