"""Consolidated prompt templates for the Minsky Society of Mind architecture.

All prompt templates are defined here and imported by the modules that use them.
"""

from minsky.prompts.rooms import (
    SENSORY_PROMPT_TEMPLATE,
    PLANNING_PROMPT_TEMPLATE,
    MOTOR_PROMPT_TEMPLATE,
    SENSORY_CHAT_TEMPLATE,
    PLANNING_CHAT_TEMPLATE,
    MOTOR_CHAT_TEMPLATE,
    SENSORY_FIRST_CHAT_TEMPLATE,
    SENSORY_FIRST_PROMPT_TEMPLATE,
    SENSORY_SECOND_CHAT_TEMPLATE,
    SENSORY_SECOND_PROMPT_TEMPLATE,
    PLANNING_FIRST_CHAT_TEMPLATE,
    PLANNING_FIRST_PROMPT_TEMPLATE,
    PLANNING_SECOND_CHAT_TEMPLATE,
    PLANNING_SECOND_PROMPT_TEMPLATE,
    MOTOR_FIRST_CHAT_TEMPLATE,
    MOTOR_FIRST_PROMPT_TEMPLATE,
    MOTOR_SECOND_CHAT_TEMPLATE,
    MOTOR_SECOND_PROMPT_TEMPLATE,
)
from minsky.prompts.judges import (
    ARCHITECTURE_PREAMBLE,
    SENSORY_JUDGE_PROMPT,
    PLANNING_JUDGE_PROMPT,
    MOTOR_JUDGE_PROMPT,
    JUDGE_PROMPTS,
)
from minsky.prompts.forecast import FORECAST_PROMPT_TEMPLATE
from minsky.prompts.summarizer import SUMMARIZER_PROMPT_TEMPLATE
from minsky.prompts.t5 import format_t5_prompt, T5_INSTRUCTIONS

__all__ = [
    # Room prompts (RWKV continuation)
    "SENSORY_PROMPT_TEMPLATE",
    "PLANNING_PROMPT_TEMPLATE",
    "MOTOR_PROMPT_TEMPLATE",
    # Room prompts (chat-model instruction)
    "SENSORY_CHAT_TEMPLATE",
    "PLANNING_CHAT_TEMPLATE",
    "MOTOR_CHAT_TEMPLATE",
    # Dual-agent prompts (first/second × 3 rooms × chat/RWKV)
    "SENSORY_FIRST_CHAT_TEMPLATE",
    "SENSORY_FIRST_PROMPT_TEMPLATE",
    "SENSORY_SECOND_CHAT_TEMPLATE",
    "SENSORY_SECOND_PROMPT_TEMPLATE",
    "PLANNING_FIRST_CHAT_TEMPLATE",
    "PLANNING_FIRST_PROMPT_TEMPLATE",
    "PLANNING_SECOND_CHAT_TEMPLATE",
    "PLANNING_SECOND_PROMPT_TEMPLATE",
    "MOTOR_FIRST_CHAT_TEMPLATE",
    "MOTOR_FIRST_PROMPT_TEMPLATE",
    "MOTOR_SECOND_CHAT_TEMPLATE",
    "MOTOR_SECOND_PROMPT_TEMPLATE",
    # Judge prompts
    "ARCHITECTURE_PREAMBLE",
    "SENSORY_JUDGE_PROMPT",
    "PLANNING_JUDGE_PROMPT",
    "MOTOR_JUDGE_PROMPT",
    "JUDGE_PROMPTS",
    # Forecast
    "FORECAST_PROMPT_TEMPLATE",
    # Summarizer
    "SUMMARIZER_PROMPT_TEMPLATE",
    # T5
    "format_t5_prompt",
    "T5_INSTRUCTIONS",
]
